### ISSUE TITLE
Ik weet de regels niet meer

### ISSUE THREAD

**Issue by Gallus19** [Crures/uepp#1]
Geachte Adriaan,

wat zijn ook alweer de uber-extreem powerpesten regels?

Met vriendelijke groet en bij voorbaat dank,
Fokke de Haan

----------------
Software developer Uber exteem powerpesten Besloten Vennootschap.
De Pannelaan 68,
8660 De Panne, Belgie
+32 58 42 02 02

**Comment by Gallus19** [comment]
🐓haha het werkt

**Comment by de-echte-obama** [comment]
ik heb een pdf van sebastiaan

**Comment by Gallus19** [comment]
Zet 'm in de repo.
Met vriendelijke groet en bij voorbaat dank,
Fokke de Haan

---------------
Software developer Uber exteem powerpesten Besloten Vennootschap.
De Pannelaan 68,
8660 De Panne, Belgie
+32 58 42 02 02

**Comment by Gallus19** [comment]
Nu weet ik de regels weer dankzij de mooie wikipagina @Crures @de-echte-obama onzettend bedankt.

Met vriendelijke groeten en nogmaals mijn diepste dank,
Fokke de Haan

----------------------
Software developer Uber exteem powerpesten en Oliebollenbakker bij Plopsaland de Panne
De Pannelaan 68,
8660 De Panne, Belgie
+32 58 42 02 02
